name: 'Bump Action'
description: 'Bump the version number of the repo'
inputs:
  release_branch:
    description: 'Release Branch'
    required: true
  create_prod_build:
    description: 'Create Production Release'
    required: true
outputs:
  version:
    description: 'version'
  tag:
    description: 'tag'
  owner:
    description: 'owner'
  repo:
    description: 'repo'
runs:
  using: 'node16'
  main: 'index.js'
