file_paths:
  seed_demo: ./secrets/seed-demo.txt
  seed: ./secrets/seed.txt
  secret_demo: ./secrets/secret-demo.yml
  secret: ./secrets/secret.yml
  secret_encrypted: secret.aes
  build: ./build
  meta_file: meta.yml

sha3_hash_length: 256

bip39_word_length: 15
