name: 'Bump Version'
description: 'Bump the version number of the repo'
inputs:
  base_branch:
    description: 'Base Branch'
    required: true
  version:
    description: 'Version Number'
    required: true
  repo_token:
    description: 'Repo Token'
    required: false
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'