name: Node.js CI

on: [push]

jobs:
  gimme-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.18.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  fun:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: github hello world1
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      # - name: List files
      #   run: |
      #     ls -lha
      - uses: actions/checkout@v2
      - name: node junk
        run: |
          cd ./.github/actions/foo
          npm ci
      - name: custom action
        uses: ./.github/actions/foo
        with:
          who-to-greet: 'foo'
          branch: GITHUB_REF

#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]


#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: npm run bats


# github: 
#   action: string
#   action_path: string
#   actor: string
#   base_ref: string
#   event: object, see https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
#   event_name: string
#   event_path: string
#   head_ref: string
#   job: string
#   repository: string
#   repository_owner: string
#   run_id: string
#   run_number: string
#   run_attempt: string
#   server_url: string
#   sha: string
#   token: string
#   workflow: string - name of workflow
#   workspace: string