# This is a basic workflow that is manually triggered

name: 'Version Bump'

# Controls when the action will run. Workflow runs when manually triggered using
# the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'
      base_branch:
        description: 'Base Branch'
        default: 'master'
        required: false
      version:
        description: 'Version Number'
        # Default value if no value is explicitly provided
        # default: null
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  foo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: stack overflow demo
        run: |
          echo "Env: ${{ github.event.inputs.environment }}" 
          echo "Branch: ${{ github.event.inputs.branch }}"
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.version }}"
      - name: do node stuff
        run: |
          git checkout master
          git checkout -b bump-version-${{ github.event.inputs.version }}
          git push origin bump-version-${{ github.event.inputs.version }}
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        with:
          version: ${{ github.event.inputs.version }}



# git push origin bump-version-${{ github.event.version.name }}
# node ./.github/workflows/manual.js ${{ github.event.version.name }}