# Manually triggered Workflow
name: 'Releaser'

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release Branch'
        default: master
        required: true
      create_prod_release:
        type: boolean
        description: 'Create Production Release'
        default: false
        required: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: 'release job'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_branch }}
      - name: Get automation repo
        uses: actions/checkout@v2
        with:
          repository: herereadthis/loamscript
          ref: main
          path: ./.github/temp/loamscript
      - name: install node on release action
        run: |
          cd ./.github/temp/loamscript/release
          npm ci
      - name: Github Script
        uses: actions/github-script@v5
        env:
          branch: ${{ github.event.inputs.release_branch }}
          create_prod_release: ${{ github.event.inputs.create_prod_release }}
        with:
          script: |
            const script = require('./.github/temp/loamscript/release/index.js')
            await script({github, context, core})

