# Manually triggered Workflow
name: 'Releaser'

env:
  # Modify the following as defined by the repository.
  DEFAULT_PACKAGE_FILE: ./package.json

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release Branch'
        default: master
        required: true
      create_prod_release:
        type: choice
        description: 'Release Type'
        required: true
        default: prerelease
        options: 
        - prerelease
        - production

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: 'release job'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_branch }}
      - name: Get current package version
        run: echo "::set-output name=version::$(echo $(node -p -e $"require('${{ env.DEFAULT_PACKAGE_FILE }}').version"))"
        id: version
      - name: Get automation repo
        uses: actions/checkout@v2
        with:
          repository: herereadthis/loamscript
          ref: main
          path: ./.github/temp/loamscript
      - name: Github Script
        uses: actions/github-script@v5
        env:
          branch: ${{ github.event.inputs.release_branch }}
          create_prod_release: ${{ github.event.inputs.create_prod_release }}
          release_version: ${{ steps.version.outputs.version }}
        with:
          script: |
            const {version} = require('${{ env.DEFAULT_PACKAGE_FILE }}')
            core.warning(version)
            const script = require('./.github/temp/loamscript/release/index.js')
            await script({github, context, core})

