# Manually triggered Workflow
name: 'Releaser'

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release Branch'
        required: true
      create_prod_build:
        type: boolean
        description: 'Create Production Release'
        default: false
        required: true

jobs:
  verify_inputs:
    runs-on: ubuntu-latest
    name: 'Verify inputs'
    steps:
      - name: Show inputs
        run: |
          echo "release branch: $RELEASE_BRANCH"
          echo "create production build: $CREATE_PROD_BUILD"
        env:
          RELEASE_BRANCH: ${{ github.event.inputs.release_branch }}
          CREATE_PROD_BUILD: ${{ github.event.inputs.create_prod_build }}
  release_job:
    runs-on: ubuntu-latest
    name: 'release job'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_branch }}
      - name: install node on release action
        run: |
          cd ./.github/actions/release
          npm ci
      - name: run release action
        uses: ./.github/actions/release
        id: release_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_branch: ${{ github.event.inputs.base_branch }}
          create_prod_build: ${{ github.event.inputs.create_pull_request }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Outputs
        run: |
          echo "The version is $VERSION"
          echo "The new version number is $NEW_VERSION_NUMBER"
          echo "The new bump branch is $NEW_BRANCH"
        env:
          VERSION: ${{ steps.release_action.outputs.version }}

