# Manually triggered Workflow
name: 'Version Bump'

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base Branch'
        default: 'master'
        required: false
      version:
        type: choice
        description: Version
        options: 
          - major
          - minor
          - patch
        required: true
      create_pull_request:
        type: boolean
        description: 'Create bump pull request'
        default: true
        required: false

jobs:
  # gimme-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJSON(github) }}
  #       run: echo "$GITHUB_CONTEXT"
  inputs:
    runs-on: ubuntu-latest
    name: 'Verify inputs'
    steps:
      - name: Show inputs
        run: |
          echo "version: $VERSION"
          echo "base branch: $BASE_BRANCH"
          echo "create pull request: $CREATE_PULL_REQUEST"
        env:
          VERSION: ${{ github.event.inputs.version }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
          CREATE_PULL_REQUEST: ${{ github.event.inputs.create_pull_request }}
  bump-commit:
    name: 'Bump Version Commit'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_pull_request == 'false' }}
    outputs:
      new_version_number: ${{ steps.bump_action.outputs.new_version_number }}
    steps:
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        id: bump_action
        with:
          version: ${{ github.event.inputs.version }}
          base_branch: ${{ github.event.inputs.base_branch }}
          create_pull_request: ${{ github.event.inputs.create_pull_request }}
      - name: Get Outputs
        run: |
          echo "The base branch is $BASE_BRANCH"
          echo "The new version number is $NEW_VERSION_NUMBER"
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      - name: Commit and Push
        # commit and push: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        run: |
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump version to $NEW_VERSION_NUMBER"
          git push origin $BASE_BRANCH
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-commit-pr:
    name: 'Bump Version + Pull Request'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_pull_request == 'true' }}
    outputs:
      new_branch: ${{ steps.bump_action.outputs.new_branch }}
      new_version_number: ${{ steps.bump_action.outputs.new_version_number }}
    steps:
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        id: bump_action
        with:
          version: ${{ github.event.inputs.version }}
          base_branch: ${{ github.event.inputs.base_branch }}
      - name: Get Outputs
        run: |
          echo "The new version number is $NEW_VERSION_NUMBER"
          echo "The new bump branch is $NEW_BRANCH"
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          NEW_BRANCH: ${{ steps.bump_action.outputs.new_branch }}
      - name: Commit and Push
        # commit and push: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        run: |
          echo "The version number is $NEW_VERSION_NUMBER"
          echo "The new branch is $NEW_BRANCH"
          echo "The base branch is $BASE_BRANCH"
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump Version $NEW_VERSION_NUMBER"
          git push origin $NEW_BRANCH
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          NEW_BRANCH: ${{ steps.bump_action.outputs.new_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create pull request
        run: gh pr create --base $BASE_BRANCH --title "$TITLE" --body-file "$TEMPLATE"
        env:
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
          TITLE: Bump Version ${{ steps.bump_action.outputs.new_version_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMPLATE: .github/PULL_REQUEST_TEMPLATE/bump-version.md
  # push:
  #   needs: [bump]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: checkout branch
  #       run: |
  #         git fetch origin
  #         git branch
  #         git checkout $NEW_BRANCH
  #         git branch
  #       env:
  #         NEW_BRANCH: ${{needs.bump.outputs.new_branch}}
  #         BASE_BRANCH: ${{ github.event.inputs.base_branch }}
  #     - name: Get Outputs
  #       run: |
  #         echo "The version number is $NEW_VERSION_NUMBER"
  #         echo "The new branch is $NEW_BRANCH"
  #         echo "The base branch is $BASE_BRANCH"
  #       env:
  #         NEW_VERSION_NUMBER: ${{needs.bump.outputs.new_version_number}}
  #         NEW_BRANCH: ${{needs.bump.outputs.new_branch}}
  #         BASE_BRANCH: ${{ github.event.inputs.base_branch }}
  #     - name: create pull request
  #       run: gh pr create --base $BASE_BRANCH --title "$TITLE" --body-file "$TEMPLATE"
  #       env:
  #         BASE_BRANCH: ${{ github.event.inputs.base_branch }}
  #         TITLE: Bump Version ${{needs.bump.outputs.new_version_number}}
  #         BODY: New version bump ${{needs.bump.outputs.new_version_number}}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TEMPLATE: .github/PULL_REQUEST_TEMPLATE/bump-version.md
  #     - name: output of bump job
  #       run: |
  #         echo "${{needs.bump.outputs.new_branch}}"
