# This is a basic workflow that is manually triggered
name: 'Version Bump'

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      base_branch:
        description: 'Base Branch'
        default: 'master'
        required: false
      version:
        type: choice
        description: Version
        options: 
          - major
          - minor
          - patch
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gimme-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  bump:
    name: 'Bump Version'
    runs-on: ubuntu-latest
    outputs:
      new_branch: ${{ steps.bump_action.outputs.new_branch }}
      new_version_number: ${{ steps.bump_action.outputs.new_version_number }}
    steps:
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        id: bump_action
        with:
          version: ${{ github.event.inputs.version }}
          base_branch: ${{ github.event.inputs.base_branch }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Outputs
        run: |
          echo "The version number is $NEW_VERSION_NUMBER"
          echo "The bump branch is $NEW_BRANCH"
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          NEW_BRANCH: ${{ steps.bump_action.outputs.new_branch }}
      - name: Commit and Push
        run: |
          git branch
          git commit -am "Bump Version $NEW_VERSION_NUMBER"
          git push origin $NEW_BRANCH
        env:
          NEW_VERSION_NUMBER: ${{ steps.bump_action.outputs.new_version_number }}
          NEW_BRANCH: ${{ steps.bump_action.outputs.new_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push:
    needs: [bump]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout branch
        run: |
          git fetch origin
          git branch
          git checkout $BRANCH_NAME
        env:
          NEW_BRANCH: ${{needs.bump.outputs.new_branch}}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      - name: create pull request
        run: gh pr create --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
        env:
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
          TITLE: Bump Version ${{ github.event.inputs.version }}
          BODY: New version bump ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: output of bump job
        run: |
          echo "${{needs.bump.outputs.new_branch}}"
