# This is a basic workflow that is manually triggered
name: 'Version Bump'

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      base_branch:
        description: 'Base Branch'
        default: 'master'
        required: false
      version:
        description: 'Version Number'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gimme-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  bump:
    name: 'Bump Version'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      newBranch: ${{ steps.bump_action.outputs.newBranch }}"
    steps:
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        id: bump_action
        with:
          version: ${{ github.event.inputs.version }}
          base_branch: ${{ github.event.inputs.base_branch }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: what is the branch?
        run: |
          git branch
      - name: Get the output branch
        run: echo "The bump branch is ${{ steps.bump_action.outputs.newBranch }}"
  push:
    needs: [bump]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout branch
        run: |
          git fetch origin
          git branch
          git checkout $BRANCH_NAME
        env:
          BRANCH_NAME: bump-version-${{ github.event.inputs.version }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      # - name: create pull request
      #   run: gh pr create --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
      #   env:
      #     BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      #     TITLE: Bump Version ${{ github.event.inputs.version }}
      #     BODY: New version bump ${{ github.event.inputs.version }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: output of bump job
        run: |
          echo "${{needs.bump.outputs.newBranch}}"
