# This is a basic workflow that is manually triggered
name: 'Version Bump'

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      base_branch:
        description: 'Base Branch'
        default: 'master'
        required: false
      version:
        description: 'Version Number'
        # Default value if no value is explicitly provided
        # default: null
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gimme-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: Dump secrets
      #   env:
      #     SECRETS: ${{ toJSON(secrets) }}
      #   run: echo "$SECRETS"
  bump:
    name: 'Bump Version'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node on bump action
        run: |
          cd ./.github/actions/bump
          npm ci
      - name: run bump action
        uses: ./.github/actions/bump
        # uses: herereadthis/guosim@v1.0
        with:
          version: ${{ github.event.inputs.version }}
          base_branch: ${{ github.event.inputs.base_branch }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: what is the branch?
        run: |
          git branch
  push:
    needs: [bump]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list variables
        run: |
          echo "$BRANCH_NAME"
          echo "BASE_BRANCH"
        env:
          BRANCH_NAME: bump-version-${{ github.event.inputs.version }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      - name: what is the branch?
        run: |
          git fetch origin
          git branch
          git checkout $BRANCH_NAME
        env:
          BRANCH_NAME: bump-version-${{ github.event.inputs.version }}
          BASE_BRANCH: ${{ github.event.inputs.base_branch }}
      # - run: gh pr create --base ${{ github.event.inputs.base_branch }} --title "Bump version ${versionNumber}" --body "new version bump ${versionNumber}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ISSUE: ${{ github.event.issue.html_url }}
  # push:
  #   name: 'Push Bump Branch'
  #   needs: [bump]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: install node on push action
  #       run: |
  #         cd ./.github/actions/push
  #         npm ci
  #     - name: run push action
  #       uses: ./.github/actions/push
  #       with:
  #         version: ${{ github.event.inputs.version }}
  #         base_branch: ${{ github.event.inputs.base_branch }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
